---
# Intall pre-requesites
- name: SELlinx
  package: name=selinux-policy state=latest


- block:
    - name: Install FirewallD
      package: name=firewalld state=latest
    - name: start firewalld
      service: name=firewalld state=restarted enabled=yes
  when: fail2ban_use_firewalld
# tasks file for fail2ban

- name: install fail2ban package
  package: name=fail2ban state={{ fail2ban_pkg_state }}
  tags: fail2ban

- name: template jail2ban jail.local configuration file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    group: root
    owner: root
    mode: 0644
    backup: yes
  notify: restart_fail2ban
  tags: fail2ban

- name: template filter  filter.d configuration files
  template:
    src: filter.conf.j2
    dest: /etc/fail2ban/filter.d/{{ item.name }}.conf
    group: root
    owner: root
    mode: 0644
    backup: yes
  notify: restart_fail2ban
  tags: fail2ban
  with_items: "{{ fail2ban_filters }}"
  when: fail2ban_filters is defined

- name: template action  action.d configuration files
  template:
    src: action.conf.j2
    dest: /etc/fail2ban/action.d/{{ item.name }}.conf
    group: root
    owner: root
    mode: 0644
    backup: yes
  notify: restart_fail2ban
  tags: fail2ban
  with_items: "{{ fail2ban_actions }}"
  when: fail2ban_actions is defined

- name: start/stop fail2ban service
  service:
    name: fail2ban
    state: '{{ fail2ban_svc_state }}'
    enabled: '{{ fail2ban_svc_enabled }}'
  tags: fail2ban
